### ISSUE TITLE
BluzDK -- setup() always called before Particle.connected()==true

### ISSUE THREAD

**Issue by gruvin** [bluzDK/bluzDK-firmware#19] opened 2016-05-16 14:12 UTC
BluzDK (v1.1.47) appears to always call setup _before_  `Particle.connected()==true`, regardless of SYSTEM_MODE setting. (Does SYSTEM_MODE even default to AUTOMATIC on BLuz as it does on Particle devices?)

The only trouble with this is that things like `Particle.subscribe(...)` cannot be simply palced in `setup()` as the Particle documents recommend. 

The workaround I have used is a one-shot in `loop()` like ...

``` C++
void loop() {
    static one_shot = true;
    if (one_shot && Particle.connected()) {
        one_shot = false;
        Particle.subscribe(...);
    }
}
```

I have not tested, but I guessing `setup()` is called once `BLE.connected()==true`. But really I think, it should be both -- or some variation of that, based on `SYSTEM_MODE(AUTOMATIC|SEMI_AUTOMATIC|MANUAL)`, perhaps.

---

Completeness:
- [X] Minimum test case added
- [X] Device, system and user firmware versions stated
- [ ] @eric The Great confirmed

**Comment by eely22** [comment] 2016-05-17 01:15
I am pretty sure this is caused by the same underlying issue in #1. Basically, we don't call Spark_Protocol_Init until after we connect to the cloud, which isn't correct. I have tried at various times to update the main function, but it hangs in a weird state.

So the same reason subscribe can't be called in setup() is the same reason that calling Particle.publish before you are connected will cause hangs. I will leave this one open to verify that, but I beleive it is two symptoms of the same underlying problem.

**Comment by gruvin** [comment] 2016-05-17 20:20
That makes perfect sense to me.

**Comment by eely22** [comment] 2016-05-17 20:36
This issue is actually a giant pain. It seems so simple to move the Spark_Init function in the main file, but it causes very strange behavior that eventually causes bluz to try and call a function at a random memory address which leads to a hang and the WDT reatarting the system. Still trying to find the root cause.

**Comment by eely22** [comment] 2016-05-18 02:47
This is FINALLY fixed! It was a duplicate of #1, the underlying problem was the same. I verified both issues are fixed with the following sketch:

``` C++
#include "application.h"

#define TIME_BETWEEN_PUBLISH 15000
int timeLastPublished = 0;

void myHandler(const char *event, const char *data) {
    Particle.publish("Incoming", "WebHook event handled!");
}

void setup() {
    pinMode(D7, OUTPUT);
    digitalWrite(D7, HIGH);
    delay(500);
    digitalWrite(D7, LOW);
    Particle.subscribe("subscribe-test", myHandler, MY_DEVICES);
}

void loop() {
    if (millis() - timeLastPublished > TIME_BETWEEN_PUBLISH)
    {
        Particle.publish("subscribe-test", "trigger!", PRIVATE);
        timeLastPublished = millis();
    }
     System.sleep(SLEEP_MODE_CPU);
}
```

This shows the the Particle.subscribe is being called properly in setup() and it does work. I also removed the check around Particle.publish, so that verifies that it can be called now without hanging the system when not connected. All working fine.

Fix is checked into the develop branch

**Closed as completed by eely22** 2016-05-18 02:47 UTC
Labels: bug

**Comment by gruvin** [comment] 2016-05-19 10:36
Awesome! :-)

**Comment by gruvin** [comment] 2016-05-19 22:40
Oh but ... actually, we're not quite there yet -- assuming the above fix was committed to `bluzDK/BluzDK-firmware:develop` ...

Whilst `Particle.publish()` in `setup()` doesn't hang the system anymore, it also just doesn't actually publish.

Also, the following will cause the system to never connect and just hang inside of `setup()` ...

``` C++
setup()
{
  waitUntil(Particle.connected);
  ...
}
```

... all of which suggests, I think, that `setup()` is being called from main() at an inappropriate time.

Oh and, `timer.start();` in my current Timer test app doesn't work in `setup()`, either.

Sorry! :-/

More specifically, this sketch works ...

``` C++
void timerCallback()
{
  if (!Particle.connected()) return; // shouldn't be needed. Will be fixed some day soon, I'm sure
  digitalWrite(D7, 1);
  Particle.publish("Timer (class of 2016)", String(millis()) );
  delay(200);
  digitalWrite(D7, 0);
}

Timer testTimer(5000, timerCallback);

/* executes once at startup */
void setup() {
  pinMode(D7, OUTPUT);  

//  Particle.publish("I'm back!", String(millis()) );
//  testTimer.start();

}

/* executes continuously after setup() runs */
void loop() {
  static bool one_shot = true;
  if (one_shot && Particle.connected()) {
    one_shot = false;

    Particle.publish("I'm back!", String(millis()) );
    testTimer.start();
  }

}
```

While this one doesn't crash during setup() -- but does end up disconnecting (according to Particle Dashboard) **even though the Bluz LED keeps flashing cyan**, as if it were connected ...

``` C++
void timerCallback()
{
  if (!Particle.connected()) return; // shouldn't be needed. Will be fixed some day soon, I'm sure
  digitalWrite(D7, 1);
  Particle.publish("Timer (class of 2016)", String(millis()) );
  delay(200);
  digitalWrite(D7, 0);
}

Timer testTimer(5000, timerCallback);

/* executes once at startup */
void setup() {
  pinMode(D7, OUTPUT);  

  Particle.publish("I'm back!", String(millis()) );
  testTimer.start();

}

/* executes continuously after setup() runs */
void loop() {
}
```

**Comment by eely22** [comment] 2016-05-19 23:27
Bluz works differently then the Photon by design. We intentionally execute user code immediately, whereas the Photon connects to the cloud first. Because of that, putting a Particle.publish inside of setup won't work since there is practically no way that the system would be connected by that point. This is by design, we wanted bluz to work even if the system wasn't connected since Bluetooth may not always be as available as WiFi.

Same goes for waitUntil. That won't work as blocking the main Conest will prevent connections from happening. The Photon and Electron get around this now by using RTOS, but that call won't work with bluz and also isn't necessary.

As for the timer issue, I will get that merged in tonight and test it out. Could be something else, not sure, but that sketch should work and we can get that issue fixed.

**Comment by gruvin** [comment] 2016-05-20 02:31
Understood @eric. 

Obviously then, Bluz does not intend to implement, `SYSTEM_MODE()`? We could though, couldn't we? Right now we have a blend of AUTOMATIC and MANUAL -- or something. {shrug}

I didn't realise it was _the_ RTOS -- as in _FreeRTOS_. I just thought it was Particle's implementation of _an_ RTOS, in a folder so named, just because.  I simply didn't look. That said, I don't see why any basic state machine in user land could not achieve about the same thing, much more safely, as in atomically. It's not like we're loading and killing off multiple programs. Newcomers to FreeRTOS must surely get themselves tied in knots around race conditions, eh? ;-)

In any case, now I know what Photon's RTOS is, I also understand why it's of no use to us -- battery!!

**Comment by eely22** [comment] 2016-05-20 02:44
@gruvin Actually, system_mode is still used, just not the SEMI_AUTOMATIC mode. If you set system mode to AUTOMATIC, then bluz tries to connect to the cloud whenever the BLE connection is established. If you use MANUAL mode, then it simply won't try and connect to the cloud. The latter is much better for local communication or instances where you don't want the cloud but still need the BLE link.

Bluz is setup so the main loop calls setup() and loop(). If the user drops in code to loop() that completely blocks the main context from running, then I don't know there is a lot we can do to stop it. A simple while(1) { } loop in loop() would stop the cloud connection. The LED and BLE events are driven by interrupts, so they would still work, but the Particle cloud maintenance is handled in the main context and the user has access to disrupt that. At the end of the day, we can't stop someone from bringing the whole thing crashing down, just try to make it as hard as possible :-)

**Comment by gruvin** [comment] 2016-05-20 02:51
@eely22 

Hmmm. OK about system_mode ... except that I don't see the currently MO as following any of the modes, as a default. It's not AUTOMATIC, as you explained earlier. But it's not manual, either ... and it certainly isn't SEMI_AUTOMATIC.

When _exactly_ then is `setup()` called? I'm now guessing that must be very soon after basic system initialisation and should only be used for things like `pinMode`, `Serial.begin`, `timer.start()` and other non-blocking code, yes?

So connections are handled in the main context on Bluz and neither `main` or `setup` should ever block. Got it.

I make too many assumptions, like the one where I thought the entire reason for having a `waitFor()` and a `waitUntil()` was to NOT block background stuff while we're waiting! Gosh. I suppose we could re-implement them, rather than forking the documentation. Put an mcu sleep in there and only interrupt into the loop a couple times a second or something?

Oh and we can't fudge a solution to keep things going via interrupt if main is blocked ... because that would just drain the battery, by continuously keeping the thing awake, no matter what the heck. Got it.

We could fork GCC and replace while/do/for with our own versions!! LOL :-P NOT.

**Comment by eely22** [comment] 2016-05-20 03:01
Yup, setup() is called right after the system is initialized. Yes, the system mode of bluz is a little different. I think the use case is different, though, so that is why we changed it a little. Think of a wearable application, the device may power on infrequently to check something, see if there is a connection, and then power off it can't connect. There wouldn't be constant WiFi as the device is moving around. And the user may not always be nearby.

Maybe it is a bit too confusing, it just seemed this was the best way to do it for BLE. Plus, advertising mode kills the battery. When the device powers on, it is just advertising and so the user, by default, needs a way to turn that off if they want. So I didn't think a mode like AUTOMATIC makes sense since you may just sit there waiting for the battery to die.

I have purposely not documented the SYSTEM_MODES yet, so this could still be changed without having to re-explain it. I am certainly open to hearing if you would like to leave it or change it.
